<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-rodrigoromanguzman/blob/main/module_5_IBM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h2>IBM module 5 | Rodrigo Ildefonso Roman Guzman |A01794225|Jobish</h2>

<h3> - Numpy Arrays -</h3>

<p>Numpy is the basis for Pandas.</p>
<b>The elements of a numpy array are all of the same type</p>

In [3]:
import numpy as np
a = np.array([0,1,2,3,4,5])
print(a.size) #atributes
print(a.ndim) #dimennsion of arrays (rank)
print(a.shape) # tupple of ints indicating the size of the array in each dimension

6
1
(6,)


<h4>Indexing and slicing</h4>

In [ ]:
a[0] #access first elemnt of array
a[1:4] # access from index 1 to index 3

<h4>Basic operations</h4>

In [6]:
b = np.array([3,3,3,3,3,3])
print(a)
print(a+b) #Addition of verctors and matrices fast and directly
print(a*3) #Multiplication by a scalar
print(np.dot(a,b)) #Dot product
print(a+1) #Bradcasted addition of the scalar


[0 1 2 3 4 5]
[3 4 5 6 7 8]
[ 0  3  6  9 12 15]
45
[1 2 3 4 5 6]


<h3>Universal functions</h3>

In [7]:
print(a.mean())
print(a.max())
print(np.pi)

2.5
5
3.141592653589793


<h4>Linspace function</h4>

<p>Returns an evenly spaced array of numbers in the specified range</p>

In [11]:
x = np.linspace(-np.pi,np.pi,num=100) #(min of range, max of range, number of items in the array)
np.sin(x)

array([-1.22464680e-16, -6.34239197e-02, -1.26592454e-01, -1.89251244e-01,
       -2.51147987e-01, -3.12033446e-01, -3.71662456e-01, -4.29794912e-01,
       -4.86196736e-01, -5.40640817e-01, -5.92907929e-01, -6.42787610e-01,
       -6.90079011e-01, -7.34591709e-01, -7.76146464e-01, -8.14575952e-01,
       -8.49725430e-01, -8.81453363e-01, -9.09631995e-01, -9.34147860e-01,
       -9.54902241e-01, -9.71811568e-01, -9.84807753e-01, -9.93838464e-01,
       -9.98867339e-01, -9.99874128e-01, -9.96854776e-01, -9.89821442e-01,
       -9.78802446e-01, -9.63842159e-01, -9.45000819e-01, -9.22354294e-01,
       -8.95993774e-01, -8.66025404e-01, -8.32569855e-01, -7.95761841e-01,
       -7.55749574e-01, -7.12694171e-01, -6.66769001e-01, -6.18158986e-01,
       -5.67059864e-01, -5.13677392e-01, -4.58226522e-01, -4.00930535e-01,
       -3.42020143e-01, -2.81732557e-01, -2.20310533e-01, -1.58001396e-01,
       -9.50560433e-02, -3.17279335e-02,  3.17279335e-02,  9.50560433e-02,
        1.58001396e-01,  